### PR TITLE
Add environment variable to make jupyterlab the default UI

### PR DESCRIPTION
**Pull request by tmckayus**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [X] No

## Description

Make the jupyterlab notebook interface the default for all notebooks

### CODE REVIEW

**Comment by tmckayus** [comment]
@vpavlin ptal

**Comment by vpavlin** [comment]
This looks good, just thinking if it would make more sense to bake this into the images rather than the spawner config?

**Comment by tmckayus** [comment]
@vpavlin so I managed to build an image with this change in it, I got the following. Seems like maybe it's not as simple as adding the env var?  (I checked quay.io/odh-jupyterhub/jupyterhub-img:v0.2.5 with podman run, there is no /opt/app-root/share/jupyter)


JupyterLab Error
JupyterLab application assets not found in "/opt/app-root/share/jupyter/lab"
Please run `jupyter lab build` or use a different app directory

**Comment by vpavlin** [comment]
This is a Jupyter*HUB* image, JupyterLab is in notebook images (generic, tensorflow...), so the way to test it is to spawn a notebook server using this version of JH image as spawner - does it make sense?

**Comment by vpavlin** [comment]
@tmckayus Any luck?

**Comment by tmckayus** [comment]
> @tmckayus Any luck?

@vpavlin it looks like setting this in an environment file in the notebook images themselves works, trying to verify now. That would allow us to set it in minimal-notebook, and inherit it in the others.  If so we can close this PR

**Comment by vpavlin** [comment]
Yeah, that was what I tried to say in my original comment (https://github.com/red-hat-data-services/jupyterhub-odh/pull/2#issuecomment-809430098) :)

**Comment by tmckayus** [comment]
> Yeah, that was what I tried to say in my original comment ([#2 (comment)](https://github.com/red-hat-data-services/jupyterhub-odh/pull/2#issuecomment-809430098)) :)

@vpavlin ack, thank you :)

**Comment by tmckayus** [comment]
going to close this and go the notebook dockerfile route to set the env var

**Pull request closed without merging**
