### PR TITLE
Update the urllib3 in requirements-build.in and re-run pip-compile

### PR DESCRIPTION
**Pull request by tmckayus**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

… Explain your changes.

### CODE REVIEW

**Comment by tmckayus** [comment]
@LaVLaS @anishasthana @harshad16 

this urllib3 update should go in, I tested a build with this update, jhub still works :)

**Comment by anishasthana** [comment]
Is there a corresponding JIRA issue we can refer to?

**Review by harshad16 — APPROVED** [review]
lgtm

**Review by anishasthana — APPROVED** [review]

**Pull request merged**
