### PR TITLE
Update oauthenticator dependency

### PR DESCRIPTION
**Pull request by tmckayus**
Include https://github.com/opendatahub-io/oauthenticator/pull/7

## Related Issues and Dependencies
    
    Include https://github.com/opendatahub-io/oauthenticator/pull/7
…

## This introduces a breaking change

- [ ] Yes
- [ X] No

## This Pull Request implements

… Explain your changes.

### CODE REVIEW

**Comment by tmckayus** [comment]
@crobby @vpavlin ptal

Includes https://github.com/opendatahub-io/oauthenticator/pull/7 (merged)

**Review by crobby — APPROVED** [review]
lgtm even though the aicoe pipeline failed

**Comment by vpavlin** [comment]
lgtm

**Pull request merged**
