### PR TITLE
[UPSTREAM] Modify image gathering for custom namespaces

### PR DESCRIPTION
**Pull request by maroroman**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2240
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

Testing same as #64 except jupyterhub should be deployed with a custom namespace for notebooks.

### CODE REVIEW

**Comment by maroroman** [comment]
After this commit is merged it is necessary to also change requirements.in to allow only jupyterhub<2.0

**Comment by crobby** [comment]
> before this commit is merged it is necessary to also change requirements.in to allow only jupyterhub<2.0

@tmckayus @samuelvl ^^^?

**Review by crobby — COMMENTED** [review]
I tried a build with this (hoping I got it right), but I'm still seeing a permission issue.  I'm hoping that I just did my live build incorrectly.  Retrying.

**Review by crobby — COMMENTED** [review]
Hmm, I think my test image was good.  Still not working though.

**Review by crobby — APPROVED** [review]
Ok, I just realized that I needed to test this with #64.  Now my test is working.

**Review by crobby — APPROVED** [review]
tested with #64, lgtm

**Pull request merged**
