### PR TITLE
Update JSP 04/20

### PR DESCRIPTION
**Pull request by VaishnaviHire**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-3182
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
Request for reviews: @LaVLaS @crobby

**Review by crobby — APPROVED** [review]
/lgtm
Looks right to me

@samuelvl  Do we need to do anything for the new addition to requirements.txt with respect to downstream?

**Comment by samuelvl** [comment]
> @samuelvl Do we need to do anything for the new addition to requirements.txt (added to JSP) with respect to downstream?

Yes, we should add the new JSP dependencies to the `requirements.in` file and generate the corresponding `requirements.txt` with pip-compile.

**Comment by LaVLaS** [comment]
@samuelvl Is `requirements-external.txt` included in the `pip-compile` execution? If not, do we need submit a follow-up PR to add the contents for `requirements-external.txt` to `requirements.in`?

**Comment by samuelvl** [comment]
> @samuelvl Is `requirements-external.txt` included in the `pip-compile` execution? If not, do we need submit a follow-up PR to add the contents for `requirements-external.txt` to `requirements.in`?

The new dependency in the [JSP requirements.txt](https://github.com/VaishnaviHire/jupyterhub-singleuser-profiles/blob/b340688f3e0237a0bf6d5ccfd7a442374936a02f/requirements.txt) file (prometheus-api-client) has to be added to the [requirements.in](https://github.com/red-hat-data-services/jupyterhub-odh/blob/master/requirements.in) this repository.

Then, regenerate the corresponding [requirements.txt](https://github.com/red-hat-data-services/jupyterhub-odh/blob/master/requirements.txt) with pipcompile.

**Comment by VaishnaviHire** [comment]
Updated the `requirements.in` and `requirements.txt` files in separate commit. This also include changes in `requirements.txt` file when jupyterhub was pinned to `>1.5, <2.0`

**Comment by samuelvl** [comment]
> Updated the `requirements.in` and `requirements.txt` files in separate commit. This also include changes in `requirements.txt` file when jupyterhub was pinned to `>1.5, <2.0`

Looks good, however the requirements.txt should be generated with the same Python version than used to build the image in CPaaS to avoid dependency conflicts. 

We are using `registry.redhat.io/ubi8/python-38:latest` so you can do:

```
$ podman run --rm -it -v $PWD:/app:z --user=0 --entrypoint=/bin/bash --workdir=/app registry.redhat.io/ubi8/python-38:latest
$ python --version
Python 3.8.8
$ python -m pip install pip-tools
$ pip-compile --allow-unsafe --generate-hashes requirements.in
```

**Review by samuelvl — APPROVED** [review]

**Pull request merged**
